(() => {
  const app = document.getElementById("app");
  const path = location.pathname;
  if (path.includes("/account")) return renderAccount();
  if (path.includes("/delivery") || path.includes("/returns") || path.includes("/contacts")) return renderService();
  GG.init("cart"); renderCart();
  function renderCart(){ const t=GG.cartTotals(); app.innerHTML = `<div class="breadcrumbs"><a href="/storefront/">Главная</a><span>/</span><span>Корзина</span></div><h1>Корзина</h1><section class="cart-layout section"><div>${t.items.length ? t.items.map(itemHtml).join("") : `<div class="panel">Корзина пуста. <a href="/storefront/catalog/">Открыть каталог</a></div>`}</div><aside class="panel sticky"><h2>Итого</h2><div data-summary>${GG.summaryHtml()}</div><label class="field"><span>Промокод</span><input class="input" data-promo placeholder="GARAGE8" value="${GGState.getPromo() || ""}"></label><button class="btn secondary full" data-apply-promo>Применить</button><a class="btn full section" href="/storefront/checkout/">Перейти к оформлению</a></aside></section>`; }
  function itemHtml(i){ const p=i.product; const flags=[]; if(p.flags.priceChanged) flags.push("изменилась цена"); if(p.flags.deliveryChanged) flags.push("изменился срок"); if(p.flags.out) flags.push("товар закончился"); if(p.flags.analogSuggested) flags.push("предложен аналог"); return `<article class="card cart-item" data-cart-item="${p.id}"><img src="${p.image}" alt="${p.name}"><div><div class="product-meta"><b>${p.brand}</b><span>${p.article}</span></div><h3>${p.name}</h3><span class="status ${GG.compatClass[p.compatibility]}">${GG.compatText[p.compatibility]}</span><p class="muted">Получение: ${p.deliveryDate} · ${p.quality} · ${p.stock ? `остаток ${p.stock} шт.` : "нет в наличии"}</p><div class="chips">${flags.map(f=>`<span class="chip active">${f}</span>`).join("")}</div><p><button class="btn ghost" data-remove="${p.id}">Удалить</button><button class="btn ghost" data-favorite="${p.id}">В избранное</button><a class="btn ghost" href="/storefront/catalog/?category=${p.category}">Подобрать аналог</a></p></div><aside><div class="qty"><button data-dec="${p.id}">-</button><input readonly value="${i.qty}"><button data-inc="${p.id}">+</button></div><p class="price">${GG.money(p.price*i.qty)}</p></aside></article>`; }
  app.addEventListener("click", (e)=>{ const cart=GGState.getCart(); const inc=e.target.closest("[data-inc]"); const dec=e.target.closest("[data-dec]"); const rem=e.target.closest("[data-remove]"); if(inc){ cart.find(x=>x.id===inc.dataset.inc).qty++; GGState.setCart(cart); renderCart(); GG.updateHeader(); } if(dec){ const it=cart.find(x=>x.id===dec.dataset.dec); it.qty=Math.max(1,it.qty-1); GGState.setCart(cart); renderCart(); GG.updateHeader(); } if(rem){ GGState.setCart(cart.filter(x=>x.id!==rem.dataset.remove)); renderCart(); GG.updateHeader(); } if(e.target.closest("[data-apply-promo]")){ const code=app.querySelector("[data-promo]").value.trim().toUpperCase(); GGState.setPromo(code==="GARAGE8"?code:null); renderCart(); } });
  function renderAccount(){ GG.init("account"); const page=path.endsWith("orders.html")?"orders":path.endsWith("vehicles.html")?"vehicles":path.endsWith("vin-requests.html")?"vin":"overview"; const side = [["overview","Обзор","/storefront/account/"],["orders","Заказы","/storefront/account/orders.html"],["vehicles","Автомобили","/storefront/account/vehicles.html"],["vin","VIN-заявки","/storefront/account/vin-requests.html"],["fav","Избранное","/storefront/catalog/?favorites=1"],["addr","Адреса","/storefront/checkout/"],["profile","Профиль","/storefront/account/"]]; const v=GGState.getVehicle(); const draft=GGState.getVinDraft(); app.innerHTML=`<div class="breadcrumbs"><a href="/storefront/">Главная</a><span>/</span><span>Кабинет</span></div><section class="account-layout"><aside class="panel account-sidebar">${side.map(([id,l,h])=>`<a class="${page===id?'active':''}" href="${h}">${l}</a>`).join("")}</aside><main>${accountBody(page,v,draft)}</main></section>`; }
  function accountBody(page,v,draft){ if(page==="orders") return `<h1>Заказы</h1><div class="section">${GG.data.orders.map(o=>`<article class="panel section"><h3>${o.id}</h3><p>${o.date} · ${o.status}</p><b>${GG.money(o.total)}</b></article>`).join("")}</div>`; if(page==="vehicles") return `<h1>Автомобили</h1><article class="panel section"><h3>${v.brand} ${v.model}</h3><p class="muted">${v.year}, ${v.engine}</p><a class="btn" href="/storefront/vehicle/">Изменить</a></article>`; if(page==="vin") return `<h1>VIN-заявки</h1>${[...(draft?[draft]:[]),...GG.data.vinRequests].map(r=>`<article class="panel section"><h3>${r.id}</h3><p>${r.status} · ${r.sla}</p><p class="muted">${r.need || r.car || "Тестовая заявка"}</p></article>`).join("")}`; return `<h1>Личный кабинет</h1><div class="dashboard-grid section"><article class="panel"><h3>Текущий заказ</h3><p>GG-10240 · готов к выдаче</p><a class="btn secondary" href="/storefront/account/orders.html">Открыть</a></article><article class="panel"><h3>Сохраненный автомобиль</h3><p>${v.brand} ${v.model}, ${v.year}</p><a class="btn secondary" href="/storefront/account/vehicles.html">Автомобили</a></article><article class="panel"><h3>Открытая VIN-заявка</h3><p>${draft ? draft.id : "VIN-24071"}</p><a class="btn secondary" href="/storefront/account/vin-requests.html">VIN-заявки</a></article></div><div class="feature-grid section"><article class="panel"><h3>Повторная покупка</h3><p class="muted">Добавьте позиции из прошлого заказа в корзину.</p></article><article class="panel"><h3>Рекомендуемое действие</h3><p class="muted">Проверьте совместимость товаров с выбранным авто.</p></article><article class="panel"><h3>Избранное</h3><p>${GGState.getFavorites().length} товаров</p></article><article class="panel"><h3>История поиска</h3><p class="muted">${GGState.getSearchHistory().join(", ")}</p></article></div>`; }
  function renderService(){ const active=path.includes("delivery")?"delivery":path.includes("returns")?"returns":"contacts"; GG.init(active); const content={ delivery:["Доставка и получение","Выберите пункт выдачи, курьера или транспортную компанию при оформлении. Сроки в storefront тестовые и зависят от выбранной позиции в mock-каталоге.","Пункты выдачи", GG.data.pickupPoints.map(p=>`${p.title}: ${p.address}, ${p.schedule}`).join("<br>")], returns:["Возврат и проверка","Если деталь не устанавливалась и сохранена упаковка, менеджер подскажет порядок возврата. Для спорных случаев понадобится номер заказа и фото товара.","Перед заказом", "Проверяйте статус совместимости. Если есть сомнения, отправьте VIN-заявку до оплаты."], contacts:["Контакты","Тестовая страница связи G-Garage для storefront. Реальные звонки, чат и обращения к CRM в этой задаче не подключены.","Как связаться", "+7 900 000-00-00<br>parts@example.test<br>Москва, тестовый пункт выдачи"] }[active]; app.innerHTML=`<div class="breadcrumbs"><a href="/storefront/">Главная</a><span>/</span><span>${content[0]}</span></div><section class="service-layout"><article class="panel"><h1>${content[0]}</h1><p>${content[1]}</p><h2>${content[2]}</h2><p class="muted">${content[3]}</p></article><aside class="panel sticky"><h3>Быстрые действия</h3><a class="btn full" href="/storefront/vin/">VIN-запрос</a><a class="btn secondary full section" href="/storefront/catalog/">Открыть каталог</a><div class="map-box section">Локальная схема без внешних карт</div></aside></section>`; }
})();

