(() => {
  const app = document.getElementById("app");
  if (location.pathname.includes("order-success")) { GG.init("cart"); return success(); }
  GG.init("cart"); render();
  function render(){ const t=GG.cartTotals(); const draft=GGState.getCheckoutDraft(); app.innerHTML=`<div class="breadcrumbs"><a href="/storefront/">Главная</a><span>/</span><span>Оформление</span></div><h1>Оформление заказа</h1><section class="checkout-layout section"><form class="panel" id="checkout"><h2>1. Контактные данные</h2><label class="field"><span>Имя</span><input class="input" name="name" required value="${draft.name||""}"></label><label class="field"><span>Телефон</span><input class="input" name="phone" required value="${draft.phone||""}"></label><label class="field"><span>Email</span><input class="input" name="email" type="email" value="${draft.email||""}"></label><h2>2. Способ доставки</h2><label class="field"><span>Доставка</span><select class="select" name="delivery"><option>Пункт выдачи</option><option>Курьер</option><option>Транспортная компания</option></select></label><label class="field"><span>Адрес или пункт выдачи</span><select class="select" name="address">${GG.data.pickupPoints.map(p=>`<option>${p.title} · ${p.address}</option>`).join("")}</select></label><label class="field"><span>Дата</span><input class="input" name="date" type="date" required value="${draft.date||"2026-07-22"}"></label><h2>3. Оплата</h2><label class="field"><span>Способ оплаты</span><select class="select" name="payment"><option>При получении</option><option>Тестовая онлайн-оплата</option></select></label><label class="field"><span>Комментарий</span><textarea name="comment">${draft.comment||""}</textarea></label><label><input type="checkbox" name="agree" required> Согласен с условиями тестового оформления</label><div data-errors></div><button class="btn full section">Создать заказ</button></form><aside class="panel sticky"><h2>Ваш заказ</h2>${t.items.map(i=>`<p><b>${i.product.brand}</b> ${i.product.name} × ${i.qty}</p>`).join("")}${GG.summaryHtml()}</aside></section>`; app.querySelector("#checkout").addEventListener("input", save); app.querySelector("#checkout").addEventListener("submit", submit); }
  function save(e){ GGState.setCheckoutDraft(Object.fromEntries(new FormData(e.currentTarget).entries())); }
  function submit(e){ e.preventDefault(); save(e); const errors=app.querySelector("[data-errors]"); if(!e.target.reportValidity()){ errors.innerHTML=`<p class="error-text">Заполните обязательные поля. Форма сохранена.</p>`; return; } sessionStorage.setItem("gg.lastOrder", `GG-${Date.now().toString().slice(-5)}`); location.href="/storefront/order-success/"; }
  function success(){ const id=sessionStorage.getItem("gg.lastOrder")||"GG-TEST"; app.innerHTML=`<section class="panel"><span class="status ok">Заказ создан</span><h1>${id}</h1><p>Тестовый заказ сохранен локально. Реальная оплата, авторизация и backend не подключались.</p><a class="btn" href="/storefront/account/orders.html">Перейти к заказам</a> <a class="btn secondary" href="/storefront/catalog/">Вернуться в каталог</a></section>`; }
})();
