(() => {
  GG.init("vehicle");
  const app = document.getElementById("app");
  let current = { brand: "", model: "", year: "", engine: "" };
  const brands = [...new Set(GG.data.vehicles.map((v) => v.brand))];
  app.innerHTML = `<div class="breadcrumbs"><a href="/storefront/">Главная</a><span>/</span><span>Подбор по авто</span></div><section class="vehicle-flow"><div class="panel"><h1>Выбор автомобиля</h1><p class="muted">Сохраненный автомобиль будет показан в header и использован в каталоге.</p><div class="stepper"><span data-step="brand" class="active">Марка</span><span data-step="model">Модель</span><span data-step="year">Год</span><span data-step="engine">Двигатель</span></div><div data-options class="option-grid"></div><div class="section"><button class="btn secondary" data-vin>Не знаю двигатель или модификацию</button></div></div><aside class="panel sticky"><h2>Текущий выбор</h2><div data-current></div><button class="btn full" data-save disabled>Сохранить автомобиль</button><a class="btn secondary full section" href="/storefront/catalog/?fit=1">Перейти в совместимый каталог</a></aside></section>`;
  const options = app.querySelector("[data-options]"), currentBox = app.querySelector("[data-current]"), save = app.querySelector("[data-save]");
  function step(){ if(!current.brand) return "brand"; if(!current.model) return "model"; if(!current.year) return "year"; if(!current.engine) return "engine"; return "done"; }
  function available(){ const s=step(); if(s==="brand") return brands; const veh=GG.data.vehicles.find((v)=>v.brand===current.brand); if(s==="model") return [veh.model]; if(s==="year") return veh.years; if(s==="engine") return veh.engines; return []; }
  function render(){ const s=step(); app.querySelectorAll("[data-step]").forEach((el)=>{ el.classList.toggle("active", el.dataset.step===s); el.classList.toggle("done", !!current[el.dataset.step] && el.dataset.step!==s); }); options.innerHTML = available().map((x)=>`<button data-pick="${x}">${x}</button>`).join("") || `<div class="notice">Автомобиль выбран. Сохраните его или перейдите в каталог.</div>`; currentBox.innerHTML = `<p><b>${[current.brand,current.model,current.year,current.engine].filter(Boolean).join(" ") || "Пока не выбран"}</b></p><p class="muted">${JSON.stringify(GGState.getVehicle())}</p>`; save.disabled = step()!=="done"; }
  app.addEventListener("click", (e)=>{ const pick=e.target.closest("[data-pick]"); if(pick){ const s=step(); current[s]=pick.dataset.pick; if(s==="brand"){ current.model=""; current.year=""; current.engine="";} render(); } if(e.target.closest("[data-save]")){ GGState.setVehicle(current); GG.updateHeader(); location.href="/storefront/catalog/?fit=1"; } if(e.target.closest("[data-vin]")) location.href="/storefront/vin/"; }); render();
})();
