(() => {
  GG.init("vin");
  const app = document.getElementById("app");
  const draft = GGState.getVinDraft();
  function form(){ app.innerHTML = `<div class="breadcrumbs"><a href="/storefront/">Главная</a><span>/</span><span>VIN-запрос</span></div><section class="form-grid"><form class="panel" id="vin-form"><h1>VIN-подбор</h1><label class="field"><span>VIN</span><input class="input" name="vin" minlength="8" required placeholder="JTNB11HK0K3000000"></label><label class="field"><span>Имя</span><input class="input" name="name" required></label><label class="field"><span>Телефон</span><input class="input" name="phone" required></label><label class="field"><span>Какая деталь нужна</span><textarea name="need" required></textarea></label><label class="field"><span>Предпочтение</span><select class="select" name="quality"><option>Надежный аналог</option><option>Оригинал</option><option>Бюджетный вариант</option></select></label><label class="field"><span>Срочность</span><select class="select" name="urgency"><option>Сегодня</option><option>1-2 дня</option><option>Без спешки</option></select></label><label class="field"><span>Фото СТС</span><input class="input" type="file" name="photo" accept="image/*"></label><button class="btn">Отправить заявку</button></form><aside class="panel sticky"><h2>Как это работает</h2><div class="doc-preview">Пример зоны VIN в документе</div><div class="timeline" style="grid-template-columns:1fr"><article><div class="step-num">1</div><b>Заполните форму</b><p class="muted">VIN, контакт и описание детали.</p></article><article><div class="step-num">2</div><b>Менеджер проверит каталоги</b><p class="muted">В этой версии результат тестовый и локальный.</p></article><article><div class="step-num">3</div><b>Ответ в рабочее время</b><p class="muted">Обычно до конца дня, без передачи данных внешним API.</p></article></div></aside></section>`; app.querySelector("#vin-form").addEventListener("submit", submit); }
  function success(req){ app.innerHTML = `<section class="panel"><span class="status ok">Заявка отправлена</span><h1>${req.id}</h1><p>Статус: <b>${req.status}</b></p><p class="muted">Ожидаемый срок ответа: ${req.sla}. Данные сохранены только в localStorage.</p><a class="btn" href="/storefront/account/vin-requests.html">Перейти к заявке</a> <a class="btn secondary" href="/storefront/contacts/">Связаться с менеджером</a></section>`; }
  function submit(e){ e.preventDefault(); if(!e.target.reportValidity()) return; const fd=Object.fromEntries(new FormData(e.target).entries()); const req={ id:`VIN-${Date.now().toString().slice(-5)}`, status:"Новая", sla:"ответ до конца рабочего дня", ...fd }; GGState.setVinDraft(req); success(req); }
  draft ? success(draft) : form();
})();
